required = [
  "github.com/alecthomas/gometalinter",
  "github.com/vektra/mockery/cmd",
  "github.com/cweill/gotests/gotests",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.9.1"
