// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package testrunner

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTestCaseRunnerInterface is an autogenerated mock type for the TestCaseRunnerInterface type
type MockTestCaseRunnerInterface struct {
	mock.Mock
}

// RunTestCase provides a mock function with given fields: ctx, input
func (_m *MockTestCaseRunnerInterface) RunTestCase(ctx context.Context, input string) (string, error) {
	ret := _m.Called(ctx, input)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
